---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-content-pv-claim
  labels:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
